<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AI-Film-Studio</AssemblyName>
    <RootNamespace>AI.FilmStudio</RootNamespace>
    <Version>1.5.3</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Embedded/AIStudioService.exe" LogicalName="AIStudioService.exe" Condition="Exists('Embedded/AIStudioService.exe')" />
    <EmbeddedResource Include="Embedded/ffmpeg.exe" LogicalName="AIStudioFFmpeg.exe" Condition="Exists('Embedded/ffmpeg.exe')" />
    <EmbeddedResource Include="Embedded/ffprobe.exe" LogicalName="AIStudioFFprobe.exe" Condition="Exists('Embedded/ffprobe.exe')" />
  </ItemGroup>
</Project>
